#./simulate.sh
# This script runs multiple simulation cases in sequence
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 5 --ki 0.1 --network 4 --case 1 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 5 --ki 0.1 --network 4 --case 2 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm ripple_control --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.1 --network 4 --case 3 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 10 --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.1 --network 4 --case 4 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.1 --network 4 --case 5 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.1 --network 4 --case 6 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 40 --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.1 --network 4 --case 7 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 50 --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 25 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study tcl_control --season 1 --days 1.25 --timestep 1.0 --ki 0.1 --network 4 --case 200 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study tcl_control --season 1 --days 1.25 --timestep 1.0 --ki 0.1 --network 4 --case 201 --flex 100 --delay 1 --tcl_control setpoint --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study tcl_control --season 1 --days 1.25 --timestep 1.0 --ki 0.1 --network 4 --case 202 --flex 100 --delay 1 --tcl_control mixed --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1.0 --ki 0.1 --network 4 --case 203 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1.0 --ki 0.1 --network 4 --case 204 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm basic_ldc --distribution per_device --ranking static --resolution 0  &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.8 --network 4 --case 17 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target 33.33 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.8 --network 4 --case 20 --flex 100 --delay 1 --tcl_control mixed --adoption 1.0 --target 33.33 --algorithm advanced_ldc --distribution per_house --ranking dynamic --resolution 3 &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 8 --flex 100 --delay 1 --tcl_control direct --adoption 0.1 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 9 --flex 100 --delay 1 --tcl_control direct --adoption 0.2 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 10 --flex 100 --delay 1 --tcl_control direct --adoption 0.3 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 11 --flex 100 --delay 1 --tcl_control direct --adoption 0.4 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 12 --flex 100 --delay 1 --tcl_control direct --adoption 0.5 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 13 --flex 100 --delay 1 --tcl_control direct --adoption 0.6 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 14 --flex 100 --delay 1 --tcl_control direct --adoption 0.7 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 15 --flex 100 --delay 1 --tcl_control direct --adoption 0.8 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 16 --flex 100 --delay 1 --tcl_control direct --adoption 0.9 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static --resolution 0  &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 1.3 --network 4 --case 18 --flex 100 --delay 1 --tcl_control mixed --adoption 1.0 --target 33.33 --algorithm basic_ldc --distribution per_device --ranking static --resolution 0  &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1.3 --ki 32 --network 4 --case 19 --flex 100 --delay 1 --tcl_control mixed --adoption 1.0 --target auto --algorithm basic_ldc --distribution per_device --ranking dynamic --resolution 0  &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study hierarchy --season 1 --days 7 --timestep 3 --ki 32 --network 4 --case 300 --flex 100 --delay 1 --tcl_control direct --adoption 1 --target auto --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&


### DER
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 400 --flex 50 --delay 1 --tcl_control direct --adoption 0.0 --target 33.33 --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 401 --flex 50 --delay 1 --tcl_control direct --adoption 0.0 --target 33.33 --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.1 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 402 --flex 50 --delay 1 --tcl_control direct --adoption 0.0 --target 33.33 --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.2 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 403 --flex 50 --delay 1 --tcl_control direct --adoption 0.0 --target 33.33 --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.3 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 404 --flex 50 --delay 1 --tcl_control direct --adoption 0.0 --target 33.33 --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 501 --flex 50 --delay 1 --tcl_control direct --adoption 1.0 --target 33.33 --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.1 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 502 --flex 50 --delay 1 --tcl_control direct --adoption 1.0 --target 33.33 --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.2 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 503 --flex 50 --delay 1 --tcl_control direct --adoption 1.0 --target 33.33 --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.3 --battery 0 --solar 0 --wind 0 &&
cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 504 --flex 50 --delay 1 --tcl_control direct --adoption 1.0 --target 33.33 --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0 --solar 0 --wind 0 &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 1 --days 2 --timestep 1 --ki 0.8 --network 4 --case 701 --flex 100 --delay 1 --tcl_control direct --adoption 0.0 --target 33.33 --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.0 --battery 0 --solar 0.3 --wind 0 &&



### ardrmore
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.1 --network 1 --case 4 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 0.1 --network 1 --case 5 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&



### for exploring different resolution of ldc_signal sensor
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 1 --timestep 1 --network 1 --case 23 --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static  &&  # resolution is 10 hz
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 1 --timestep 1 --network 1 --case 22 --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&  # resolution is 1 hz
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 1 --timestep 1 --network 1 --case 24 --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 6  &&  # resolution is 1 micro hz

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 1 --timestep 1 --network 2 --case 23 --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static  &&  # resolution is 10 hz
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 1 --timestep 1 --network 2 --case 22 --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 0  &&  # resolution is 1 hz
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 1 --timestep 1 --network 2 --case 24 --adoption 1.0 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 6  &&  # resolution is 1 micro hz



# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --network 1 --case 3 --adoption 1 --target 50 --algorithm basic_ldc --distribution per_house --ranking static   &&

### dickert_lv_long
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --network 3 --case 3 --adoption 1 --target 50 --algorithm basic_ldc --distribution per_house --ranking static   &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --network 3 --case 1 --adoption 1 --target auto --algorithm no_ldc --distribution per_house --ranking static  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --network 3 --case 4 --adoption 1 --target 75 --algorithm basic_ldc --distribution per_house --ranking static   &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --network 3 --case 2 --adoption 1 --target auto --algorithm ripple_control --distribution per_house --ranking static  &&

### ieee_european_lv
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.1 --network 4 --case 25 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 1  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.1 --network 4 --case 20 --adoption 1 --target 30 --algorithm advanced_ldc --distribution per_device --ranking dynamic --resolution 1  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.1 --network 4 --case 19 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_device --ranking dynamic --resolution 1  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.1 --network 4 --case 3 --adoption 1 --target 50 --algorithm basic_ldc --distribution per_house --ranking static --resolution 1  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 1 --network 4 --case 4 --adoption 1 --target 75 --algorithm basic_ldc --distribution per_house --ranking static --resolution 1  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 1 --network 4 --case 2 --adoption 1 --target tou --algorithm ripple_control --distribution per_house --ranking static --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 1 --network 4 --case 18 --adoption 1 --target 40 --algorithm basic_ldc --distribution per_house --ranking static --resolution 1  &&


# ### Ki studies
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 50 --network 4 --case 200 --tcl_control mixed --adoption 1 --target tou --algorithm no_ldc --distribution per_house --ranking static --resolution 3  &&
# ## ramp tests
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 16 --network 4 --case 101 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 32 --network 4 --case 102 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 64 --network 4 --case 103 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 128 --network 4 --case 104 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 256 --network 4 --case 105 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 4 --case 106 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 1024 --network 4 --case 107 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 2048 --network 4 --case 108 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 4096 --network 4 --case 109 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 8192 --network 4 --case 110 --adoption 1 --target 100 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&

# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 10 --network 4 --case 111 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 20 --network 4 --case 112 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 30 --network 4 --case 113 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 40 --network 4 --case 114 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 50 --network 4 --case 115 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 60 --network 4 --case 116 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 70 --network 4 --case 117 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 80 --network 4 --case 118 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 90 --network 4 --case 119 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 100 --network 4 --case 120 --adoption 1 --target 30 --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&

# ### direct control of TCL
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 32 --network 4 --case 31 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 1 --ki 32 --network 4 --case 32 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 5 --ki 32 --network 4 --case 33 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 16 --network 4 --case 121 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 32 --network 4 --case 122 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 64 --network 4 --case 123 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 128 --network 4 --case 124 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 256 --network 4 --case 125 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 4 --case 126 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 1024 --network 4 --case 127 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 2048 --network 4 --case 128 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 4096 --network 4 --case 129 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 8192 --network 4 --case 130 --tcl_control direct --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&

# ### setpoint control of TCL
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 16 --network 4 --case 131 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 32 --network 4 --case 132 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 64 --network 4 --case 133 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 128 --network 4 --case 134 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 526 --network 4 --case 135 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 4 --case 136 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 1024 --network 4 --case 137 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 80 --network 4 --case 138 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 90 --network 4 --case 139 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 100 --network 4 --case 140 --tcl_control setpoint --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&

# ### setpoint2 control of TCL
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 10 --network 4 --case 141 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 32 --network 4 --case 142 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 30 --network 4 --case 143 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 40 --network 4 --case 144 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 50 --network 4 --case 145 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 60 --network 4 --case 146 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 70 --network 4 --case 147 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 80 --network 4 --case 148 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 90 --network 4 --case 149 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 100 --network 4 --case 150 --tcl_control setpoint2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 10 --network 4 --case 201 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 32 --network 4 --case 202 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 30 --network 4 --case 203 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 40 --network 4 --case 204 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 50 --network 4 --case 205 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 60 --network 4 --case 206 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 70 --network 4 --case 207 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 80 --network 4 --case 208 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 90 --network 4 --case 209 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 100 --network 4 --case 210 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 10 --network 4 --case 211 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 20 --network 4 --case 212 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 30 --network 4 --case 213 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 40 --network 4 --case 214 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 50 --network 4 --case 215 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 60 --network 4 --case 216 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 70 --network 4 --case 217 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 80 --network 4 --case 218 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 90 --network 4 --case 219 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 100 --network 4 --case 220 --tcl_control mixed2 --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static --resolution 3  &&

### 1.75 days
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 1 --ki 64 --network 4 --case 1 --delay 0 --tcl_control mixed --adoption 1 --target auto --algorithm no_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 64 --network 4 --case 2 --tcl_control mixed --adoption 1 --target auto --algorithm ripple_control --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 64 --network 4 --case 223 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 256 --network 4 --case 224 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 4 --case 225 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 1024 --network 4 --case 226 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 4 --case 231 --delay 0.1 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 4 --case 232 --delay 1 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 4 --case 233 --delay 2 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.3 --ki 256 --network 4 --case 243 --delay 1 --tcl_control mixed --adoption 1 --target 50 --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.3 --ki 256 --network 4 --case 244 --delay 1 --tcl_control mixed --adoption 1 --target 50 --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.3 --ki 256 --network 4 --case 245 --delay 1 --tcl_control mixed --adoption 1 --target 50 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.3 --ki 256 --network 4 --case 246 --delay 1 --tcl_control mixed --adoption 1 --target 50 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.1 --ki 256 --network 4 --case 255 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.1 --ki 256 --network 4 --case 253 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.1 --ki 256 --network 4 --case 254 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 0.1 --ki 256 --network 4 --case 256 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1 --ki 256 --network 4 --case 1 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm no_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1 --ki 256 --network 4 --case 2 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm ripple_control --distribution per_house --ranking static  --resolution 0 &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 1.3 --ki 256 --network 4 --case 277 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 1.0 --ki 256 --network 4 --case 276 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.1 --ki 256 --network 4 --case 271 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.2 --ki 256 --network 4 --case 272 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.3 --ki 256 --network 4 --case 273 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.5 --ki 256 --network 4 --case 274 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.1 --timestep 0.8 --ki 256 --network 4 --case 275 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 5 --ki 32 --network 4 --case 1 --flex 0 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm no_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 5 --ki 32 --network 4 --case 2 --flex 0 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm ripple_control --distribution per_house --ranking static  --resolution 0 &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 0.9 --ki 128 --network 4 --case 301 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 0.9 --ki 128 --network 4 --case 302 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 8 --network 4 --case 291 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target auto --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 32 --network 4 --case 290 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 50 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&

# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study hierarchy --season 2 --days 7 --timestep 3 --ki 0.1 --network 4 --case 300 --flex 100 --delay 1 --tcl_control direct --adoption 1 --target auto --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 0.1 --network 4 --case 292 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 33 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 0.2 --network 4 --case 293 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 33 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 0.5 --network 4 --case 294 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 33 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 2.0 --network 4 --case 295 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 33 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 5.0 --network 4 --case 296 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 33 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 3 --timestep 1.5 --ki 10.0 --network 4 --case 297 --flex 100 --delay 1 --tcl_control mixed --adoption 1 --target 33 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&


# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.3 --timestep 0.3 --ki 128 --network 4 --case 280 --flex 0 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.3 --timestep 0.3 --ki 128 --network 4 --case 279 --flex 0 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm basic_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.3 --timestep 0.3 --ki 128 --network 4 --case 281 --flex 10 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.3 --timestep 0.3 --ki 128 --network 4 --case 283 --flex 30 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.3 --timestep 0.3 --ki 128 --network 4 --case 285 --flex 50 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.3 --timestep 0.3 --ki 128 --network 4 --case 287 --flex 70 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.3 --timestep 0.3 --ki 128 --network 4 --case 289 --flex 90 --delay 1 --tcl_control mixed --adoption 1 --target 20 --algorithm advanced_ldc --distribution per_house --ranking static  --resolution 0 &&

# ### lv 5
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 1 --ki 64 --network 1 --case 1 --delay 0 --tcl_control mixed --adoption 1 --target auto --algorithm no_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 7 --timestep 1 --ki 64 --network 1 --case 2 --tcl_control mixed --adoption 1 --target auto --algorithm ripple_control --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 64 --network 1 --case 223 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 256 --network 1 --case 224 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 1 --case 225 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 1024 --network 1 --case 226 --delay 0.5 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 1 --case 231 --delay 0.1 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 1 --case 232 --delay 1 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
# cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 1 --days 0.05 --timestep 0.1 --ki 512 --network 1 --case 233 --delay 2 --tcl_control mixed --adoption 1 --target tou --algorithm basic_ldc --distribution per_house --ranking static  --resolution 1 &&
	
#   ### decrease resolution

# # 1:'no_ldc',
# # 2:'ripple_control',
# # 3:'loading_50', 
# # 4:'loading_75', 
# # 5:'loading_auto', 
# # 6:'per_house',  # adoption 50, target auto
# # 7:'per_device', # adoption 50, target auto
# # 8:'adoption_10',
# # 9:'adoption_20',
# # 10:'adoption_30',
# # 11:'adoption_40',
# # 12:'adoption_50',
# # 13:'adoption_60',
# # 14:'adoption_70',
# # 15:'adoption_80',
# # 16:'adoption_90',
# # 17:'adoption_100',
# # 18:'basic_ldc_waterheater',
# # 19:'basic_ldc_dynamic', 
# # 20:'advanced_ldc'}
# ### summer
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 3 --adoption 1 --target auto &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 4 --adoption 1 --target auto &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 5 --adoption 1 --target 50 &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 5 --adoption 1 --target 75 &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 5 --adoption 1 --target auto &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 6 --adoption 1 --target 50 &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 6 --adoption 1 --target 75 &&
# # cd /home/pi/ldc_project/ldc_simulator/ && /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --season 2 --days 7 --timestep 10 --network 2 --case 6 --adoption 1 --target auto &&
### end
cd /home/pi/ldc_project/ldc_simulator/