#./simulate.sh
### This script runs multiple simulation cases in sequence
### batt
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1101 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.1 --battery 0.1 --solar 0.1 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1102 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.2 --battery 0.2 --solar 0.2 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1103 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.3 --battery 0.3 --solar 0.3 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1104 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.4 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1105 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.5 --battery 0.5 --solar 0.5 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1106 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.6 --battery 0.6 --solar 0.6 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1107 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.7 --battery 0.7 --solar 0.7 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1108 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.8 --battery 0.8 --solar 0.8 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1109 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.9 --battery 0.9 --solar 0.9 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.8 --network 2 --case 1110 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 1.0 --battery 1.0 --solar 1.0 --wind 0 &&

# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1200 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.0 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1201 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.04 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1202 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.08 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1203 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.12 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1204 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.16 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1205 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.20 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1206 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.24 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1207 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.28 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1208 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.32 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 10 --ki 0.1 --network 2 --case 1209 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.36 --solar 0.4 --wind 0 &&
# /home/pi/anaconda3/bin/python MAIN.py --simulate 1 --study DER --season 3 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1210 --flex 100 --delay 1.0 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.4 --solar 0.4 --wind 0 &&

### DER winter
/home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1004 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.0 --solar 0.4 --wind 0 &&
/home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 904 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.4 --battery 0.0 --solar 0.4 --wind 0 &&

# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 901 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.1 --battery 0.0 --solar 0.1 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 902 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.2 --battery 0.0 --solar 0.2 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 903 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.3 --battery 0.0 --solar 0.3 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 905 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.5 --battery 0.0 --solar 0.5 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 906 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.6 --battery 0.0 --solar 0.6 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 907 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.7 --battery 0.0 --solar 0.7 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 908 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.8 --battery 0.0 --solar 0.8 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 909 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 0.9 --battery 0.0 --solar 0.9 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 910 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm no_ldc --distribution per_house --ranking static --resolution 3  --ev 1.0 --battery 0.0 --solar 1.0 --wind 0 &&

# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1001 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.1 --battery 0.0 --solar 0.1 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1002 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.2 --battery 0.0 --solar 0.2 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1003 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.3 --battery 0.0 --solar 0.3 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1005 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.5 --battery 0.0 --solar 0.5 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1006 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.6 --battery 0.0 --solar 0.6 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1007 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.7 --battery 0.0 --solar 0.7 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1008 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.8 --battery 0.0 --solar 0.8 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1009 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 0.9 --battery 0.0 --solar 0.9 --wind 0 &&
# /home/pi/anaconda3/bin/python main.py --simulate 1 --study DER --season 1 --days 3 --timestep 1 --ki 0.8 --network 2 --case 1010 --flex 100 --delay 1 --tcl_control direct --adoption 1.0 --target auto --algorithm advanced_ldc --distribution per_house --ranking static --resolution 3  --ev 1.0 --battery 0.0 --solar 1.0 --wind 0 &&



cd /home/pi/ldc_project/ldc_simulator/